export const URL = {
  CREATE_USER: 'https://blooming-fjord-89301.herokuapp.com/signup',
  FETCH_USER: 'https://blooming-fjord-89301.herokuapp.com/auth/login',
  FETCH_CATEGORIES: 'https://blooming-fjord-89301.herokuapp.com/admin/categories',
  FETCH_PRODUCTS: 'https://blooming-fjord-89301.herokuapp.com/admin/products',
  CREATE_PRODUCT: 'https://blooming-fjord-89301.herokuapp.com/admin/products',
  UPDATE_PRODUCT: 'https://blooming-fjord-89301.herokuapp.com/admin/products',
  DELETE_PRODUCT: 'https://blooming-fjord-89301.herokuapp.com/admin/products',
  FETCH_FAVORITES: 'https://blooming-fjord-89301.herokuapp.com/admin/favorites',
  CREATE_FAVORITE: 'https://blooming-fjord-89301.herokuapp.com/admin/favorites',
  UPDATE_FAVORITE: 'https://blooming-fjord-89301.herokuapp.com/admin/favorites',
  DELETE_FAVORITE: 'https://blooming-fjord-89301.herokuapp.com/admin/favorites',
  FETCH_FAVORITE_PRODUCTS: 'https://blooming-fjord-89301.herokuapp.com/admin/favorite_products',
  CREATE_FAVORITE_PRODUCT: 'https://blooming-fjord-89301.herokuapp.com/admin/favorite_products',
  DELETE_FAVORITE_PRODUCT: 'https://blooming-fjord-89301.herokuapp.com/admin/favorite_products',
};
